import { ContentAsset } from "../ContentAsset";

export const TEMPLATES_CLUSTER: ContentAsset[] = [
  {
    slug: "invoice-template",
    title: "Free Invoice PDF Template",
    seoTitle: "Free Invoice PDF Template – Ready‑to‑Use for Businesses",
    metaDescription: "Download a professional invoice PDF template. Perfect for freelancers and small businesses. No registration required.",
    contentType: "template",
    category: "templates",
    cluster: "templates",
    publishedAt: "2026-07-01",
    readMinutes: 2,
    definition: "A clean, printable PDF invoice template with editable fields for items, totals, and company branding.",
    quickAnswer: "Use this ready‑made invoice template to bill clients quickly.",
    summary: "A simple, modern invoice layout that can be filled out in any PDF editor.",
    useCases: ["Freelance billing", "Small business invoicing", "Consultant contracts"],
    body: [{ type: "p", text: "Download the template, open it in your favorite PDF editor, and replace placeholder text with your own details." }]
  },
  {
    slug: "resume-template",
    title: "Professional Resume PDF Template",
    seoTitle: "Professional Resume PDF Template – Stand Out to Employers",
    metaDescription: "Free resume template in PDF format. Clean design, ATS‑friendly, ready to customize and download.",
    contentType: "template",
    category: "templates",
    cluster: "templates",
    publishedAt: "2026-07-02",
    readMinutes: 2,
    definition: "A modern, ATS‑compatible resume template with sections for experience, education, and skills.",
    quickAnswer: "Use this template to create a polished resume that passes automated screening.",
    summary: "A sleek resume layout that highlights your achievements and is easy to edit.",
    useCases: ["Job applications", "Career fairs", "LinkedIn profile export"],
    body: [{ type: "p", text: "Open the PDF in a PDF editor, replace the placeholder text, and export your final resume." }]
  },
  {
    slug: "legal-contract-template",
    title: "Legal Contract PDF Template",
    seoTitle: "Legal Contract PDF Template – Free & Customizable",
    metaDescription: "Download a free legal contract template for agreements, NDAs, and service contracts. Editable and ready to use.",
    contentType: "template",
    category: "templates",
    cluster: "templates",
    publishedAt: "2026-07-03",
    readMinutes: 3,
    definition: "A generic legal contract template covering Parties, Terms, Confidentiality, and Signatures.",
    quickAnswer: "Use this contract template for basic agreements and customize as needed.",
    summary: "A versatile legal contract that can be adapted for many business situations.",
    useCases: ["Freelance agreements", "NDA", "Service contracts"],
    body: [{ type: "p", text: "Edit the clauses to match your specific agreement and have both parties sign the PDF." }]
  },
  {
    slug: "project-proposal-template",
    title: "Project Proposal PDF Template",
    seoTitle: "Project Proposal PDF Template – Impress Clients",
    metaDescription: "Free project proposal template in PDF. Structured sections for scope, timeline, budget, and deliverables.",
    contentType: "template",
    category: "templates",
    cluster: "templates",
    publishedAt: "2026-07-04",
    readMinutes: 3,
    definition: "A proposal template designed to outline project objectives, methodology, timeline, and costs.",
    quickAnswer: "Use this template to create professional project proposals quickly.",
    summary: "A clean layout that helps you convey project details and win contracts.",
    useCases: ["Consulting bids", "Agency pitches", "Internal project planning"],
    body: [{ type: "p", text: "Fill in your project specifics, adjust the budget table, and export the final PDF." }]
  },
  {
    slug: "newsletter-template",
    title: "Newsletter PDF Template",
    seoTitle: "Newsletter PDF Template – Free Design for Updates",
    metaDescription: "Download a ready‑made newsletter PDF template. Perfect for company updates, events, and marketing communications.",
    contentType: "template",
    category: "templates",
    cluster: "templates",
    publishedAt: "2026-07-05",
    readMinutes: 2,
    definition: "A multi‑page newsletter layout with placeholders for headlines, images, and articles.",
    quickAnswer: "Use this template to create engaging newsletters in PDF format.",
    summary: "A visually appealing newsletter design ready for content insertion.",
    useCases: ["Corporate updates", "Event announcements", "Community news"],
    body: [{ type: "p", text: "Replace the sample headings and images with your own content, then export the finished newsletter." }]
  }
];
